server:
  port: 8888
spring:
  redis:
    host: 120.25.72.26
    database: 1
    password: P@ssword@redis
    port: 6379
    lettuce:
      pool:
        enabled: true
keycloak:
  realm: Rage
  bearer-only: true
  auth-server-url: https://id.ragehealth.cn/auth
  ssl-required: external
  resource: open-back
  use-resource-role-mappings: false
  principal-attribute: preferred_username
logging:
  level:
    org.springframework: debug
    org.keycloak: debug